version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # redis is used for benchmarking, since redis 5.0 use
      # redis-client under the hood, there's no point comparing it.
      - dependency-name: "redis"
        update-types: ["major"]