---
name: Test
on: [push]

jobs:
  build:
    name: "Build Redis ${{ matrix.redis }} image"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: ["6.2"]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build --tag 'ghcr.io/${{ github.repository_owner }}/redis-ci:${{ matrix.redis }}' --build-arg "BASE_IMAGE=redis:${{ matrix.redis }}" test/docker
          docker push ghcr.io/${{ github.repository_owner }}/redis-ci:${{ matrix.redis }}

  lint:
    name: Rubocop
    timeout-minutes: 30
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop

  test:
    name: Ruby ${{ matrix.ruby }} / Redis ${{ matrix.redis }}
    needs: build
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["6.2"]
        ruby: ["3.1", "3.0", "2.7", "2.6", "2.5"]
    services:
      redis:
        image: ghcr.io/${{ github.repository_owner }}/redis-ci:${{ matrix.redis }}
        ports:
          - 16379:16379
          - 26379:26379
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
